cosmos = "atom"
axlusdc = "usdc"
wrapped-bitcoin = "wbtc"
ethereum = "eth"
stride-staked-osmo = "stOsmo"
binancecoin = "bnb"
dai = "dai"
stride-staked-atom = "stAtom"
osmosis = "osmo"
inter-stable-token = "ist"
umee = "umee"